name: Go Test

on: [ push ]
jobs:
  test-go:
    runs-on: ubuntu-latest
    env:
        API_V3_KEY: ${{ secrets.API_V3_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Test
        run: make test
